apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-hang-tag-ingress
  namespace: mdp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: mdpdev-m.monsterdigital.biz
      http:
        paths:
          - path: /hang-tag
            pathType: Prefix
            backend:
              service:
                name: webapp-hang-tag
                port:
                  number: 80
