apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-qa-pod
  namespace: mdp
  labels:
    mSvc: webapp-qa-pod
spec:
  selector:
    matchLabels:
      mSvc: webapp-qa-pod
  template:
    metadata:
      labels:
        mSvc: webapp-qa-pod
    spec:
      containers:
        - name: webapp-qa-pod-container
          image: monsterdigital.azurecr.io/mdp-webapp-qa-pod:dev
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 5
